source "https://rubygems.org"

group :jekyll_plugins do
  # https://pages.github.com/versions.json
  gem "github-pages", "~> 228"
  gem "jekyll-paginate", "~> 1.1.0"
  gem "jekyll-feed", "~> 0.15.1"
end

gem "webrick", "~> 1.8"
